<?php
# *** LICENSE ***
# This file is part of BlogoText.
# Copyright (c) 2006 Frederic Nassar.
# All rights reserved.
# BlogoText is free software, you can redistribute it under the terms of the
# Creative Commons Attribution-NonCommercial-NoDerivs 2.0 France Licence
# *** LICENSE ***
$GLOBALS['langs'] = array(
		"fr" => 'Français',
		"en" => 'English'
);

$lang_fr = array(
'id'												=> 'fr',
// Install
'install'										=> 'Installation',
'install_id'								=> 'Choisissez un identifiant',
'install_mdp'								=> 'Choisissez un mot de passe',
'install_remdp'							=> 'Confirmez votre mot de passe',
'install_ok'								=> 'Félicitations ! Installation réussie',
'install_echec' 						=> 'Désolé, votre serveur n\'est pas compatible',
'install_connect' 					=> 'Identifiez-vous',
'first_titre' 							=> 'Mon premier article',
'first_edit' 								=> 'Editez-moi',
// Wiki
'label_wiki'								=> 'Mise en forme',
'wiki_titre'								=> 'Titre',
'wiki_titre_exp'						=> '! Gros titre !! Titre moyen !!! Petit titre',
'wiki_lien'									=> 'Lien',
'wiki_lien_exp'							=> '[texte du lien|URL du lien]',
'wiki_gras'									=> 'Gras',
'wiki_gras_exp'							=> '__Texte en gras__',
'wiki_italique'							=> 'Italique',
'wiki_italique_exp'					=> '{Texte en italique}',
'wiki_image'								=> 'Image',
'wiki_image_exp'						=> '((URL de l\'image|Texte alternatif))',
'wiki_lienimage' 						=> 'Lien-image',
'wiki_lienimage_exp' 				=> '[((URL de l\'image|Texte alternatif))|URL du lien]',
'wiki_souligne' 						=> 'Souligné',
'wiki_souligne_exp' 				=> '++Texte souligné++',
'wiki_barre' 								=> 'Barré',
'wiki_barre_exp' 						=> '--Texte barré--',
'wiki_code' 								=> 'Code',
// Navigation
'preferences'								=> 'Préférences',
'connexion' 								=> 'Connexion',
'enregistrer' 							=> 'Enregistrer',
'envoyer' 									=> 'Envoyer',
'mesarticles' 							=> 'Mes articles',
'nouveau' 									=> 'Nouvel article',
'supprimer' 								=> 'Supprimer',
'deconnexion' 							=> 'Déconnexion',
'rechercher' 								=> 'Rechercher',
'filtrer' 									=> 'Filtrer',
'oui' 											=> 'Oui',
'non' 											=> 'Non',
'ouverts' 									=> 'Autorisés',
'fermes' 										=> 'Interdits',
'depuis' 										=> 'depuis',
'sur' 											=> 'sur',
// Modes
'ecrire'										=> 'Modifier',
'apercu'										=> 'Apercu',
'images'										=> 'Images',
'commentaires'							=> 'Commentaire(s)',
// Labels
'label_date'								=> 'Date',
'label_time'								=> 'Heure',
'label_titre'								=> 'Titre',
'label_chapo'								=> 'Chapô',
'label_contenu'							=> 'Contenu',
'label_identifiant'					=> 'Identifiant',
'label_motdepasse'					=> 'Mot de passe',
'label_statut'							=> 'Etat',
'label_publie'							=> 'Publié',
'label_brouillon'						=> 'Brouillon',
'label_brouillons'					=> 'Brouillons',
'label_publies'							=> 'Publiés',
'label_allowcomment'				=> 'Commentaires',
'label_image_ajout'					=> 'Ajouter une image',
'label_derniers'						=> 'Articles récents',
'label_afficher'						=> 'Afficher',
'label_ok'									=> 'Ok',
'label_article'							=> 'article',
'label_articles'						=> 'articles',
'label_commentaire'					=> 'commentaire',
'label_commentaires'				=> 'commentaires',
// Commentaire
'aucun'											=> 'aucun',
'comment_ajout'							=> 'Ajouter un commentaire',
'comment_nom'								=> 'Nom',
'comment_email'							=> 'E-mail',
'comment_contenu'						=> 'Commentaire',
'comment_captcha'						=> 'Calculez la somme suivante (filtre anti-spam) :',
'comment_not_allowed'				=> 'Les commentaires sont fermés pour cette article',
// Titles - liens
'lien_article'							=> 'Voir l\'article',
'lien_blog'									=> 'Voir le blog',
// Mois
'janvier'										=> 'janvier',
'fevrier'										=> 'février',
'mars'											=> 'mars',
'avril'											=> 'avril',
'mai'												=> 'mai',
'juin'											=> 'juin',
'juillet'										=> 'juillet',
'aout'											=> 'août',
'septembre'									=> 'septembre',
'octobre'										=> 'octobre',
'novembre'									=> 'novembre',
'decembre'									=> 'décembre',
// Jours
'lu'												=> 'Lu',
'ma'												=> 'Ma',
'me'												=> 'Me',
'je'												=> 'Je',
've'												=> 'Ve',
'sa'												=> 'Sa',
'di'												=> 'Di',
// Jours
'lundi'											=> 'lundi',
'mardi'											=> 'mardi',
'mercredi'									=> 'mercredi',
'jeudi'											=> 'jeudi',
'vendredi'									=> 'vendredi',
'samedi'										=> 'samedi',
'dimanche'									=> 'dimanche',
'aujourdhui'								=> 'aujourd\'hui',
'hier'											=> 'hier',
// Erreurs
'erreurs' 									=> 'Erreur(s)',
'err_connexion' 						=> 'Identifiant et/ou mot de passe incorrect(s)',
'err_titre' 								=> 'Le titre est vide',
'err_chapo' 								=> 'Le chapô est vide',
'err_contenu' 							=> 'Le contenu est vide',
'err_annee' 								=> 'L\'année est incorrecte',
'err_mois' 									=> 'Le mois est incorrect',
'err_jour' 									=> 'Le jour est incorrect',
'err_heure' 								=> 'L\'heure est incorrecte',
'err_minutes' 							=> 'Les minutes sont incorrectes',
'err_secondes' 							=> 'Les secondes sont incorrectes',
'err_id_exist' 							=> 'Cet identifiant existe déjà, merci de modifier la date de publication',
'err_data_dir_notfound' 		=> 'Le dossier data est introuvable',
'err_prefs_write'				 		=> 'Ecriture impossible du fichier des préférences',
'err_prefs_auteur'					=> 'Le nom de l\'auteur est vide',
'err_prefs_email'						=> 'L\'adresse e-mail n\'est pas valide',
'err_prefs_identifiant'			=> 'Le nom d\'utilisateur est vide',
'err_prefs_id_mdp'					=> 'Pour définir un nouvel identifiant, vous devez saisir votre mot de passe',
'err_prefs_oldmdp'					=> 'L\'ancien mot de passe n\'est pas valide',
'err_prefs_mdp'							=> 'Le mot de passe doit faire au moins 6 caractères',
'err_prefs_newmdp'					=> 'Pour définir un nouveau mot de passe, vous devez saisir l\'ancien',
'err_prefs_nbmax'						=> 'Le nombre d\'articles n\'est pas valide',
'err_prefs_racine'					=> 'Vous devez indiquer l\'URL du blog',
'err_prefs_racine_http'			=> 'L\'URL du blog doit commencer par "http://"',
'err_prefs_racine_slash'		=> 'L\'URL du blog doit finir par un slash "/"',
'err_no_comment'						=> 'Tous les champs sont obligatoires pour déposer un commentaire',
'err_comm_auteur'						=> 'Le nom de l\'auteur est vide',
'err_comm_email'						=> 'L\'adresse e-mail n\'est pas valide',
'err_comm_contenu'					=> 'Le commentaire est vide',
'err_comm_captcha'					=> 'La somme est incorrecte',
// Questions
'question_suppr_article'		=> 'Etes-vous sûr de vouloir supprimer cet article ?',
'question_suppr_comment'		=> 'Etes-vous sûr de vouloir supprimer ce commentaire ?',
// Confirmations
'confirm_article_suppr'			=> 'L\'article a été supprimé',
'confirm_article_ajout'			=> 'L\'article a été enregistré',
'confirm_article_maj'				=> 'L\'article a été mis à jour',
'confirm_image_ajout'				=> 'L\'image a été ajoutée',
'confirm_image_suppr'				=> 'L\'image a été supprimée',
'confirm_prefs_maj'					=> 'Vos préférences ont été enregistrées',
'confirm_logout_ok'					=> 'Vous êtes bien déconnecté',
'confirm_comment_ajout'			=> 'Votre commentaire a été ajouté',
'confirm_comment_suppr'			=> 'Le commentaire a été supprimé',
// Redirections
'retour_liste'							=> '« Liste des articles',
// Titres des pages
'bienvenue'									=> 'Bienvenue',
'titre_identification' 			=> 'Veuillez vous identifier',
'titre_articles' 						=> 'Vos articles',
'titre_ecrire' 							=> 'Ecrire un nouvel article',
'titre_maj' 								=> 'Mise à jour d\'un article',
'titre_commentaires' 				=> 'Commentaires',
'titre_preferences' 				=> 'Préférences',
// Preferences
'prefs_legend_utilisateur'	=> 'Utilisateur',
'prefs_legend_apparence'		=> 'Apparence',
'prefs_legend_securite'			=> 'Sécurité',
'prefs_legend_dateheure'		=> 'Date et heure',
'prefs_legend_config'				=> 'Configuration',
'pref_auteur'								=> 'Auteur',
'pref_email'								=> 'Adresse e-mail',
'pref_identifiant'					=> 'Identifiant',
'pref_mdp'									=> 'Mot de passe actuel',
'pref_mdp_nouv'							=> 'Nouveau mot de passe',
'pref_langue'								=> 'Langue',
'pref_nom_site'							=> 'Nom du site',
'pref_desc'									=> 'Description',
'pref_format_date'					=> 'Format de date',
'pref_format_heure'					=> 'Format de l\'heure',
'pref_racine'								=> 'Adresse du blog (URL)',
'pref_dossier_images'				=> 'Emplacement des images',
'pref_nb_maxi'							=> 'Nombre d\'articles sur l\'accueil',
'pref_nb_list'							=> 'Nombre d\'articles dans la liste',
'pref_apercu'								=> 'Activer l\'aperçu',
'pref_theme'								=> 'Thème',
'pref_images'								=> 'Utiliser les images',
'pref_commentaires'					=> 'Utiliser les commentaires',
// Notes
'note_no_article'						=> 'Aucun article trouvé',
'note_no_comment'						=> 'Aucun commentaire',
'resultats_recherche'				=> 'Résultat(s) de votre recherche :',
'note_no_image'							=> 'Aucune image'
);

$lang_en = array(
'id'												=> 'en',
// Install
'install'										=> 'Installing',
'install_id'								=> 'Choose a username',
'install_mdp'								=> 'Choose a password',
'install_remdp'							=> 'Retype your passowrd',
'install_ok'								=> 'Congratulations ! Installation succeeded',
'install_echec' 						=> 'Sorry, your host is not compatible',
'install_connect' 					=> 'Sign in',
'first_titre' 							=> 'My first article',
'first_edit' 								=> 'Edit me',
// Wiki
'label_wiki'								=> 'Formatting rules',
'wiki_titre'								=> 'Title',
'wiki_titre_exp'						=> '! Big title !! Middle title !!! Small title',
'wiki_lien'									=> 'Link',
'wiki_lien_exp'							=> '[Text link|Link URL]',
'wiki_gras'									=> 'Bold',
'wiki_gras_exp'							=> '__Bold text__',
'wiki_italique'							=> 'Italic',
'wiki_italique_exp'					=> '{Italic text}',
'wiki_image'								=> 'Image',
'wiki_image_exp'						=> '((Image URL|Alternate text))',
'wiki_lienimage' 						=> 'Link-image',
'wiki_lienimage_exp' 				=> '[((Image URL|Alternate text))|Link URL]',
'wiki_souligne' 						=> 'Underline',
'wiki_souligne_exp' 				=> '++Underline text++',
'wiki_barre' 								=> 'Overline',
'wiki_barre_exp' 						=> '--Overline text--',
'wiki_code' 								=> 'Code',
// Navigation
'preferences'								=> 'Preferences',
'connexion' 								=> 'Connect',
'enregistrer' 							=> 'Save',
'envoyer' 									=> 'Send',
'mesarticles' 							=> 'My articles',
'nouveau' 									=> 'New article',
'supprimer' 								=> 'Delete',
'deconnexion' 							=> 'Logout',
'rechercher' 								=> 'Search',
'filtrer' 									=> 'Filter',
'oui' 											=> 'Yes',
'non' 											=> 'No',
'ouverts' 									=> 'Open',
'fermes' 										=> 'Closed',
'depuis' 										=> 'from',
'sur' 											=> 'of',
// Modes
'ecrire'										=> 'Edit',
'apercu'										=> 'Preview',
'images'										=> 'Images',
'commentaires'							=> 'Comment(s)',
// Labels
'label_date'								=> 'Date',
'label_time'								=> 'Time',
'label_titre'								=> 'Title',
'label_chapo'								=> 'Abstract',
'label_contenu'							=> 'Content',
'label_identifiant'					=> 'Login',
'label_motdepasse'					=> 'Password',
'label_statut'							=> 'Status',
'label_publie'							=> 'Published',
'label_brouillon'						=> 'Draft',
'label_brouillons'					=> 'Drafts',
'label_publies'							=> 'Published',
'label_allowcomment'				=> 'Comments',
'label_image_ajout'					=> 'Add an image',
'label_derniers'						=> 'Recent articles',
'label_afficher'						=> 'Show',
'label_ok'									=> 'Go',
'label_article'							=> 'article',
'label_articles'						=> 'articles',
'label_commentaire'					=> 'comment',
'label_commentaires'				=> 'comments',
// Commentaire
'aucun'											=> 'no',
'comment_ajout'							=> 'Post a comment',
'comment_nom'								=> 'Name',
'comment_email'							=> 'E-mail',
'comment_contenu'						=> 'Comment',
'comment_captcha'						=> 'Calculate this addition (anti-spam filter) :',
'comment_not_allowed'				=> 'Comments are closed for this article',
// Titles - liens
'lien_article'							=> 'View article',
'lien_blog'									=> 'View blog',
// Mois
'janvier'										=> 'january',
'fevrier'										=> 'february',
'mars'											=> 'march',
'avril'											=> 'april',
'mai'												=> 'may',
'juin'											=> 'june',
'juillet'										=> 'july',
'aout'											=> 'august',
'septembre'									=> 'september',
'octobre'										=> 'october',
'novembre'									=> 'november',
'decembre'									=> 'december',
// Jours
'lu'												=> 'Mo',
'ma'												=> 'Tu',
'me'												=> 'We',
'je'												=> 'Th',
've'												=> 'Fr',
'sa'												=> 'Sa',
'di'												=> 'Su',
// Jours
'lundi'											=> 'monday',
'mardi'											=> 'tuesday',
'mercredi'									=> 'wednesday',
'jeudi'											=> 'thursday',
'vendredi'									=> 'friday',
'samedi'										=> 'saturday',
'dimanche'									=> 'sunday',
'aujourdhui'								=> 'today',
'hier'											=> 'yesterday',
// Erreurs
'erreurs' 									=> 'Error(s)',
'err_connexion' 						=> 'Invalid login or password',
'err_titre' 								=> 'Empty title',
'err_chapo' 								=> 'Empty abstract',
'err_contenu' 							=> 'Empty content',
'err_annee' 								=> 'The year is not correct',
'err_mois' 									=> 'The month is not correct',
'err_jour' 									=> 'The day is not correct',
'err_heure' 								=> 'The hour is not correct',
'err_minutes' 							=> 'The minutes are not correct',
'err_secondes' 							=> 'The seconds are not correct',
'err_id_exist' 							=> 'This ID already exists, please modify the publishing date',
'err_data_dir_notfound' 		=> 'Can\'t find the data folder.',
'err_prefs_write'				 		=> 'Unable to write the preferences file',
'err_prefs_auteur'					=> 'The author name is missing',
'err_prefs_email'						=> 'Invalid email address',
'err_prefs_identifiant'			=> 'User name missing',
'err_prefs_id_mdp'					=> 'Please type your password to define a new username',
'err_prefs_oldmdp'					=> 'Invalid current passowrd',
'err_prefs_mdp'							=> 'Your password must be at least 6 characters long',
'err_prefs_newmdp'					=> 'To define a new password, type your current password',
'err_prefs_nbmax'						=> 'Invalid entries number',
'err_prefs_racine'					=> 'Blog URL can not be empty',
'err_prefs_racine_http'			=> 'Blog URL must start by "http://"',
'err_prefs_racine_slash'		=> 'Blog URL must end by a slash "/"',
'err_no_comment'						=> 'Every single field is required to post a comment',
'err_comm_auteur'						=> 'The author name is missing',
'err_comm_email'						=> 'Invalid email address',
'err_comm_contenu'					=> 'The comment is empty',
'err_comm_captcha'					=> 'Incorrect addition',
// Questions
'question_suppr_article'		=> 'Are you sure you want to delete this article ?',
'question_suppr_comment'		=> 'Are you sure you want to delete this comment ?',
// Confirmations
'confirm_article_suppr'			=> 'Your article has been deleted',
'confirm_article_ajout'			=> 'Your article has been saved',
'confirm_article_maj'				=> 'Your article has been updated',
'confirm_image_ajout'				=> 'The image has been uploaded',
'confirm_image_suppr'				=> 'The image has been deleted',
'confirm_prefs_maj'					=> 'Your preferences have been saved',
'confirm_logout_ok'					=> 'You have been disconnected',
'confirm_comment_ajout'			=> 'Your comment has been added',
'confirm_comment_suppr'			=> 'The comment has been deleted',
// Redirections
'retour_liste'							=> '« List of articles',
// Titres des pages
'bienvenue'									=> 'Welcome',
'titre_identification' 			=> 'Please login',
'titre_articles' 						=> 'Your articles',
'titre_ecrire' 							=> 'Writing a new article',
'titre_maj' 								=> 'Editing your article',
'titre_commentaires' 				=> 'Comments',
'titre_preferences' 				=> 'Preferences',
// Preferences
'prefs_legend_utilisateur'	=> 'User',
'prefs_legend_apparence'		=> 'Appearance',
'prefs_legend_securite'			=> 'Security',
'prefs_legend_dateheure'		=> 'Time and date',
'prefs_legend_config'				=> 'Configuration',
'pref_auteur'								=> 'Author',
'pref_email'								=> 'Email',
'pref_identifiant'					=> 'User name',
'pref_mdp'									=> 'Current password',
'pref_mdp_nouv'							=> 'New password',
'pref_langue'								=> 'Language',
'pref_nom_site'							=> 'Site name',
'pref_desc'									=> 'Description',
'pref_format_date'					=> 'Date format',
'pref_format_heure'					=> 'Time format',
'pref_racine'								=> 'Blog URL',
'pref_dossier_images'				=> 'Images location',
'pref_nb_maxi'							=> 'Number of articles on home page',
'pref_nb_list'							=> 'Number of articles in the list',
'pref_apercu'								=> 'Show article preview',
'pref_theme'								=> 'Theme',
'pref_images'								=> 'Use images',
'pref_commentaires'					=> 'Use comments',
// Notes
'note_no_article'						=> 'No article found',
'note_no_comment'						=> 'No comments',
'resultats_recherche'				=> 'Search result(s) :',
'note_no_image'							=> 'No image'
);

?>