<?php
# *** LICENSE ***
# This file is part of BlogoText.
# Copyright (c) 2006 Frederic Nassar.
#               2010 Timo Van Neerden
# All rights reserved.
# BlogoText is free software, you can redistribute it under the terms of the
# Creative Commons Attribution-NonCommercial-NoDerivs 2.0 France Licence
# *** LICENSE ***
$GLOBALS['langs'] = array(
		"fr" => 'Français',
		"en" => 'English',
		"nl" => 'Nederlands'
);
/* ##############################################################################################
   ----------------------------------------- Francais -----------------------------------------*/
$lang_fr = array(
'id'								=> 'fr',
// Install
'install'							=> 'Installation',
'install_id'						=> 'Choisissez un identifiant',
'install_mdp'						=> 'Choisissez un mot de passe',
'install_remdp'					=> 'Confirmez votre mot de passe',
'install_ok'						=> 'Félicitations ! Installation réussie',
'install_echec' 					=> 'Désolé, votre serveur n\'est pas compatible',
'install_connect' 				=> 'Identifiez-vous',
'first_titre' 						=> 'Mon premier article',
'first_edit' 						=> 'Éditez-moi',
// Wiki
'label_wiki'						=> 'Mise en forme',
'wiki_titre'						=> 'Titre',
'wiki_titre_exp'					=> '! Gros titre !! Titre moyen !!! Petit titre',
'wiki_lien'							=> 'Lien',
'wiki_lien_exp'					=> '[texte du lien|URL du lien]',
'wiki_gras'							=> 'Gras',
'wiki_gras_exp'					=> '__Texte en gras__',
'wiki_italique'					=> 'Italique',
'wiki_italique_exp'				=> '##Texte en italique##',
'wiki_image'						=> 'Image',
'wiki_image_exp'					=> '((src|alt|class|title))',
'wiki_lienimage' 					=> 'Lien-image',
'wiki_image_exp'						=> '((URL de l\'image|Texte alternatif))',
'wiki_souligne' 					=> 'Souligné',
'wiki_souligne_exp' 				=> '++Texte souligné++',
'wiki_barre' 						=> 'Barré',
'wiki_barre_exp' 					=> '--Texte barré--',
'wiki_code' 						=> 'Code',
// Navigation
'nouvelle_image'					=> 'Image',
'preferences'						=> 'Préférences',
'connexion' 						=> 'Connexion',
'enregistrer' 						=> 'Enregistrer',
'envoyer' 							=> 'Envoyer',
'mesarticles' 						=> 'Mes articles',
'nouveau' 							=> 'Nouvel article',
'supprimer' 						=> 'Supprimer',
'deconnexion' 						=> 'Déconnexion',
'rechercher' 						=> 'Rechercher',
'filtrer' 							=> 'Filtrer',
'oui' 								=> 'Oui',
'non' 								=> 'Non',
'ouverts' 							=> 'Autorisés',
'fermes' 							=> 'Interdits',
'depuis' 							=> 'depuis',
'sur' 								=> 'sur',
// Modes
'ecrire'								=> 'Modifier',
'apercu'								=> 'Aperçu',
'images'								=> 'Images',
'commentaires'						=> 'Commentaire(s)',
// Labels
'label_date'						=> 'Date',
'label_time'						=> 'Heure',
'label_titre'						=> 'Titre',
'label_chapo'						=> 'Chapô',
'label_contenu'					=> 'Contenu',
'label_identifiant'				=> 'Identifiant',
'label_motdepasse'				=> 'Mot de passe',
'label_statut'						=> 'État',
'label_publie'						=> 'Publié',
'label_brouillon'					=> 'Brouillon',
'label_brouillons'				=> 'Brouillons',
'label_publies'					=> 'Publiés',
'label_allowcomment'				=> 'Commentaires',
'label_image_ajout'				=> 'Ajouter une image',
'label_derniers'					=> 'Articles récents',
'label_afficher'					=> 'Afficher',
'label_ok'							=> 'Ok',
'label_article'					=> 'article',
'label_articles'					=> 'articles',
'label_commentaire'				=> 'commentaire',
'label_commentaires'				=> 'commentaires',
// Commentaire
'aucun'								=> 'aucun',
'comment_ajout'					=> 'Ajouter un commentaire',
'comment_nom'						=> 'Pseudo :',
'comment_email'					=> 'E-mail (ne sera pas publié) :',
'comment_webpage'					=> 'Site web (facultatif) :',
'comment_contenu'					=> '',
'comment_captcha'					=> 'Combien font ',
'comment_not_allowed'			=> 'Les commentaires sont fermés pour cette article',
// Titles - liens
'lien_article'						=> 'Voir l\'article',
'lien_blog'							=> 'Voir le blog',
// Mois
'janvier'							=> 'janvier',
'fevrier'							=> 'fevrier',
'mars'								=> 'mars',
'avril'								=> 'avril',
'mai'									=> 'mai',
'juin'								=> 'juin',
'juillet'							=> 'juillet',
'aout'								=> 'aout',
'septembre'							=> 'septembre',
'octobre'							=> 'octobre',
'novembre'							=> 'novembre',
'decembre'							=> 'decembre',
// Jours
'lu'									=> 'Lu',
'ma'									=> 'Ma',
'me'									=> 'Me',
'je'									=> 'Je',
've'									=> 'Ve',
'sa'									=> 'Sa',
'di'									=> 'Di',
// Jours	
'lundi'								=> 'lundi',
'mardi'								=> 'mardi',
'mercredi'							=> 'mercredi',
'jeudi'								=> 'jeudi',
'vendredi'							=> 'vendredi',
'samedi'								=> 'samedi',
'dimanche'							=> 'dimanche',
'aujourdhui'						=> 'aujourd\'hui',
'hier'								=> 'hier',
// Erreurs
'erreurs' 							=> 'Erreur(s)',
'err_connexion' 					=> 'Identifiant et/ou mot de passe incorrect(s)',
'err_titre' 						=> 'Le titre est vide',
'err_chapo' 						=> 'Le chapô est vide',
'err_contenu' 						=> 'Le contenu est vide',
'err_annee' 						=> 'L\'année est incorrecte',
'err_mois' 							=> 'Le mois est incorrect',
'err_jour' 							=> 'Le jour est incorrect',
'err_heure' 						=> 'L\'heure est incorrecte',
'err_minutes' 						=> 'Les minutes sont incorrectes',
'err_secondes' 					=> 'Les secondes sont incorrectes',
'err_id_exist' 					=> 'Cet identifiant existe déjà, merci de modifier la date de publication',
'err_data_dir_notfound' 		=> 'Le dossier data est introuvable',
'err_prefs_write'					=> 'Écriture impossible du fichier des préférences',
'err_prefs_auteur'				=> 'Le nom de l\'auteur est vide',
'err_prefs_email'					=> 'L\'adresse e-mail n\'est pas valide',
'err_prefs_identifiant'			=> 'Le nom d\'utilisateur est vide',
'err_prefs_id_mdp'				=> 'Pour définir un nouvel identifiant, vous devez saisir votre mot de passe',
'err_prefs_oldmdp'				=> 'L\'ancien mot de passe n\'est pas valide',
'err_prefs_mdp'					=> 'Le mot de passe doit faire au moins 6 caractères',
'err_prefs_newmdp'				=> 'Pour définir un nouveau mot de passe, vous devez saisir l\'ancien',
'err_prefs_nbmax'					=> 'Le nombre d\'articles n\'est pas valide',
'err_prefs_racine'				=> 'Vous devez indiquer l\'URL du blog',
'err_prefs_racine_http'			=> 'L\'URL du blog doit commencer par "http://"',
'err_prefs_racine_slash'		=> 'L\'URL du blog doit finir par un slash "/"',
'err_no_comment'					=> 'Tous les champs sont obligatoires pour déposer un commentaire',
'err_comm_auteur'					=> 'Le nom de l\'auteur est vide',
'err_comm_email'					=> 'L\'adresse e-mail n\'est pas valide',
'err_comm_contenu'				=> 'Le commentaire est vide',
'err_comm_captcha'				=> 'La somme est incorrecte',
// Questions
'question_suppr_article'		=> 'Êtes-vous sûr de vouloir supprimer cet article ?',
'question_suppr_comment'		=> 'Êtes-vous sûr de vouloir supprimer ce commentaire ?',
// Confirmations
'confirm_article_suppr'			=> 'L\'article a été supprimé',
'confirm_article_ajout'			=> 'L\'article a été enregistré',
'confirm_article_maj'			=> 'L\'article a été mis à jour',
'confirm_image_ajout'			=> 'L\'image a été ajoutée',
'confirm_image_suppr'			=> 'L\'image a été supprimée',
'confirm_prefs_maj'				=> 'Vos préférences ont été enregistrées',
'confirm_logout_ok'				=> 'Vous êtes bien déconnecté',
'confirm_comment_ajout'			=> 'Votre commentaire a été ajouté',
'confirm_comment_suppr'			=> 'Le commentaire a été supprimé',
// Redirections
'retour_liste'						=> '« Liste des articles',
// Titres des pages
'bienvenue'							=> 'Bienvenue',
'titre_identification' 			=> 'Veuillez vous identifier',
'titre_articles' 					=> 'Vos articles',
'titre_ecrire' 					=> 'Écrire un nouvel article',
'titre_maj' 						=> 'Mise à jour d\'un article',
'titre_commentaires' 			=> 'Commentaires',
'titre_preferences' 				=> 'Préférences',
'titre_image'						=> 'Envoyer une image',
// Preferences
'prefs_legend_utilisateur'		=> 'Utilisateur',
'prefs_legend_apparence'		=> 'Apparence',
'prefs_legend_securite'			=> 'Sécurité',
'prefs_legend_dateheure'		=> 'Date et heure',
'prefs_legend_config'			=> 'Configuration',
'prefs_legend_image'				=> 'Envoyer une image',
'pref_auteur'						=> 'Auteur',
'pref_email'						=> 'Adresse e-mail',
'pref_identifiant'				=> 'Identifiant',
'pref_mdp'							=> 'Mot de passe actuel',
'pref_mdp_nouv'					=> 'Nouveau mot de passe',
'pref_langue'						=> 'Langue',
'pref_nom_site'					=> 'Nom du site',
'pref_desc'							=> 'Description',
'pref_format_date'				=> 'Format de date',
'pref_format_heure'				=> 'Format de l\'heure',
'pref_racine'						=> 'Adresse du blog (URL)',
'pref_dossier_images'			=> 'Emplacement des images',
'pref_nb_maxi'						=> 'Nombre d\'articles sur l\'accueil',
'pref_nb_list'						=> 'Nombre d\'articles dans la liste',
'pref_nb_list_com'				=> 'Nombre de commentaires dans la liste',
'pref_apercu'						=> 'Activer l\'aperçu',
'pref_theme'						=> 'Thème',
'pref_images'						=> 'Utiliser les images',
'pref_commentaires'				=> 'Utiliser les commentaires',
'pref_aff_onglet_comm'			=> 'Afficher l\'onglet "Commentaires"',
'pref_aff_onglet_images'		=> 'Afficher l\'onglet "Image"',
// Notes
'note_no_article'					=> 'Aucun article trouvé',
'note_no_comment'					=> 'Aucun commentaire',
'resultats_recherche'			=> 'Résultat(s) de votre recherche :',
'note_no_image'					=> 'Aucune image',
//Formulaire Images
'img_nom_donnee'					=> 'Nom (facultatif) :',
'img_avert_format_nom'			=> '(chiffres et lettres seulement)',
'img_upload'						=> 'Envoyer',
'img_upload_succes'				=> 'L\'image a été envoyé avec succès !',

'img_err_chmod'					=> 'Impossible d\'uploader le fichier. Veuillez vérifier le CHMOD du dossier : ',
'img_err_size'						=> 'Votre fichier doit faire moins de ',
'img_err_format'					=> 'Mauvais format de fichier. Les formats autorisés sont : ',
'img_err_file'						=> 'Le fichier n\'est pas une image valide.',
'img_phperr_partial'				=> 'L\'image n\'a été que partiellement envoyée.',
'img_phperr_nofile'				=> 'Aucun fichier n\'a été spécifié.',
'img_phperr_tempfolder'			=> 'Un dossier temporaire est manquant',
'img_phperr_DiskWrite'			=> 'Échec de l\'écriture du fichier sur le disque.',

'succes'								=> "Succès",
// Chiffres 0 à 9 pour captcha
'0'									=> 'zéro',
'1'									=> 'un',
'2'									=> 'deux',
'3'									=> 'trois',
'4'									=> 'quatre',
'5'									=> 'cinq',
'6'									=> 'six',
'7'									=> 'sept',
'8'									=> 'huit',
'9'									=> 'neuf',

);
/* ##############################################################################################
   ----------------------------------------- English -----------------------------------------*/

$lang_en = array(
'id'								=> 'en',
// Install
'install'							=> 'Installing',
'install_id'						=> 'Choose a user-name',
'install_mdp'						=> 'Choose a password',
'install_remdp'					=> 'Retype your password',
'install_ok'						=> 'Congratulations ! Installation succeeded',
'install_echec' 					=> 'Sorry, your host is not compatible',
'install_connect' 				=> 'Sign in',
'first_titre' 						=> 'My first article',
'first_edit' 						=> 'Edit me',
// Wiki
'label_wiki'						=> 'Formatting rules',
'wiki_titre'						=> 'Title',
'wiki_titre_exp'					=> '! Big title !! Middle title !!! Small title',
'wiki_lien'							=> 'Link',
'wiki_lien_exp'					=> '[Text link|Link URL]',
'wiki_gras'							=> 'Bold',
'wiki_gras_exp'					=> '__Bold text__',
'wiki_italique'					=> 'Italic',
'wiki_italique_exp'				=> '##Italic text##',
'wiki_image'						=> 'Image',
'wiki_image_exp'						=> '((Image URL|Alternate text))',
'wiki_lienimage' 					=> 'Link-image',
'wiki_lienimage_exp' 			=> '[((Image URL|Alternate text))|Link URL]',
'wiki_souligne' 					=> 'Underline',
'wiki_souligne_exp' 				=> '++Underline text++',
'wiki_barre' 						=> 'strike',
'wiki_barre_exp' 					=> '--stroke text--',
'wiki_code' 						=> 'Code',
// Navigation
'nouvelle_image'					=> 'Images',
'preferences'						=> 'Preferences',
'connexion' 						=> 'Connect',
'enregistrer' 						=> 'Save',
'envoyer' 							=> 'Send',
'mesarticles' 						=> 'My articles',
'nouveau' 							=> 'New article',
'supprimer' 						=> 'Delete',
'deconnexion' 						=> 'Logout',
'rechercher' 						=> 'Search',
'filtrer' 							=> 'Filter',
'oui' 								=> 'Yes',
'non' 								=> 'No',
'ouverts' 							=> 'Open',
'fermes' 							=> 'Closed',
'depuis' 							=> 'from',
'sur' 								=> 'of',
// Modes
'ecrire'								=> 'Edit',
'apercu'								=> 'Preview',
'images'								=> 'Images',
'commentaires'						=> 'Comment(s)',
// Labels
'label_date'						=> 'Date',
'label_time'						=> 'Time',
'label_titre'						=> 'Title',
'label_chapo'						=> 'Abstract',
'label_contenu'					=> 'Content',
'label_identifiant'				=> 'Login',
'label_motdepasse'				=> 'Password',
'label_statut'						=> 'Status',
'label_publie'						=> 'Published',
'label_brouillon'					=> 'Draft',
'label_brouillons'				=> 'Drafts',
'label_publies'					=> 'Published',
'label_allowcomment'				=> 'Comments',
'label_image_ajout'				=> 'Add an image',
'label_derniers'					=> 'Recent articles',
'label_afficher'					=> 'Show',
'label_ok'							=> 'Go',
'label_article'					=> 'article',
'label_articles'					=> 'articles',
'label_commentaire'				=> 'comment',
'label_commentaires'				=> 'comments',
// Commentaire
'aucun'								=> 'no',
'comment_ajout'					=> 'Post a comment',
'comment_nom'						=> 'Name',
'comment_email'					=> 'E-mail (will not be published)',
'comment_webpage'					=> 'web site (optional)',

'comment_contenu'					=> 'Comment',
'comment_captcha'					=> 'Calculate this addition (anti-spam filter) :',
'comment_not_allowed'			=> 'Comments are closed for this article',
// Titles - liens
'lien_article'						=> 'View article',
'lien_blog'							=> 'View blog',
// Mois
'janvier'							=> 'January',
'fevrier'							=> 'February',
'mars'								=> 'March',
'avril'								=> 'April',
'mai'									=> 'May',
'juin'								=> 'June',
'juillet'							=> 'July',
'aout'								=> 'August',
'septembre'							=> 'September',
'octobre'							=> 'October',
'novembre'							=> 'November',
'decembre'							=> 'December',
// Jours
'lu'									=> 'Mo',
'ma'									=> 'Tu',
'me'									=> 'We',
'je'									=> 'Th',
've'									=> 'Fr',
'sa'									=> 'Sa',
'di'									=> 'Su',
// Jours
'lundi'								=> 'Monday',
'mardi'								=> 'Tuesday',
'mercredi'							=> 'Wednesday',
'jeudi'								=> 'Thursday',
'vendredi'							=> 'Friday',
'samedi'								=> 'Saturday',
'dimanche'							=> 'Sunday',
'aujourdhui'						=> 'today',
'hier'								=> 'yesterday',
// Erreurs
'erreurs' 							=> 'Error(s)',
'err_connexion' 					=> 'Invalid login or password',
'err_titre' 						=> 'Empty title',
'err_chapo' 						=> 'Empty abstract',
'err_contenu' 						=> 'Empty content',
'err_annee' 						=> 'The year is not correct',
'err_mois' 							=> 'The month is not correct',
'err_jour' 							=> 'The day is not correct',
'err_heure' 						=> 'The hour is not correct',
'err_minutes' 						=> 'The minutes are not correct',
'err_secondes' 					=> 'The seconds are not correct',
'err_id_exist' 					=> 'This ID already exists, please modify the publishing date',
'err_data_dir_notfound'			=> 'Can\'t find the data folder.',
'err_prefs_write'				 	=> 'Unable to write the preferences file',
'err_prefs_auteur'				=> 'The author name is missing',
'err_prefs_email'					=> 'Invalid email address',
'err_prefs_identifiant'			=> 'User name missing',
'err_prefs_id_mdp'				=> 'Please type your password to define a new username',
'err_prefs_oldmdp'				=> 'Invalid current password',
'err_prefs_mdp'					=> 'Your password must be at least 6 characters long',
'err_prefs_newmdp'				=> 'To define a new password, type your current password',
'err_prefs_nbmax'					=> 'Invalid entries number',
'err_prefs_racine'				=> 'Blog URL can not be empty',
'err_prefs_racine_http'			=> 'Blog URL must start by "http://"',
'err_prefs_racine_slash'		=> 'Blog URL must end by a slash "/"',
'err_no_comment'					=> 'Every single field is required to post a comment',
'err_comm_auteur'					=> 'The author name is missing',
'err_comm_email'					=> 'Invalid email address',
'err_comm_contenu'				=> 'The comment is empty',
'err_comm_captcha'				=> 'Incorrect addition',
// Questions
'question_suppr_article'		=> 'Are you sure you want to delete this article ?',
'question_suppr_comment'		=> 'Are you sure you want to delete this comment ?',
// Confirmations
'confirm_article_suppr'			=> 'Your article has been deleted',
'confirm_article_ajout'			=> 'Your article has been saved',
'confirm_article_maj'			=> 'Your article has been updated',
'confirm_image_ajout'			=> 'The image has been uploaded',
'confirm_image_suppr'			=> 'The image has been deleted',
'confirm_prefs_maj'				=> 'Your preferences have been saved',
'confirm_logout_ok'				=> 'You have been disconnected',
'confirm_comment_ajout'			=> 'Your comment has been added',
'confirm_comment_suppr'			=> 'The comment has been deleted',
// Redirections
'retour_liste'						=> '« List of articles',
// Titres des pages
'bienvenue'							=> 'Welcome',
'titre_identification' 			=> 'Please login',
'titre_articles' 					=> 'Your articles',
'titre_ecrire' 					=> 'Writing a new article',
'titre_maj' 						=> 'Editing your article',
'titre_commentaires' 			=> 'Comments',
'titre_preferences' 				=> 'Preferences',
'titre_image'						=> 'Upload an image',
// Preferences
'prefs_legend_utilisateur'		=> 'User',
'prefs_legend_apparence'		=> 'Appearance',
'prefs_legend_securite'			=> 'Security',
'prefs_legend_dateheure'		=> 'Time and date',
'prefs_legend_config'			=> 'Configuration',
'prefs_legend_image'				=> 'Upload an image',
'pref_auteur'						=> 'Author',
'pref_email'						=> 'Email',
'pref_identifiant'				=> 'User name',
'pref_mdp'							=> 'Current password',
'pref_mdp_nouv'					=> 'New password',
'pref_langue'						=> 'Language',
'pref_nom_site'					=> 'Site name',
'pref_desc'							=> 'Description',
'pref_format_date'				=> 'Date format',
'pref_format_heure'				=> 'Time format',
'pref_racine'						=> 'Blog URL',
'pref_dossier_images'			=> 'Images location',
'pref_nb_maxi'						=> 'Number of articles on home page',
'pref_nb_list'						=> 'Number of articles in the list',
'pref_nb_list_com'				=> 'Number of comments in the list',
'pref_apercu'						=> 'Show article preview',
'pref_theme'						=> 'Theme',
'pref_images'						=> 'Use images',
'pref_commentaires'				=> 'Use comments',
'pref_aff_onglet_comm'			=> 'Display the "Comments" tab',
'pref_aff_onglet_images'		=> 'Display the "Image" tab',
// Notes
'note_no_article'					=> 'No article found',
'note_no_comment'					=> 'No comments',
'resultats_recherche'			=> 'Search result(s) :',
'note_no_image'					=> 'No image',
//Formulaire Images
'img_nom_donnee'					=> 'New file-name (optional)',
'img_avert_format_nom'			=> '(ciffers and letters only)',
'img_upload'						=> 'Upload',
'img_upload_succes'				=> 'Image successfully uploaded.',

'img_err_chmod'					=> 'The image has not been uploaded. Please, check the destination folder\'s CHMOD : ',
'img_err_size'						=> 'The image has to be smaller than ',
'img_err_format'					=> 'Wrong image format. Allowed are : ',
'img_err_file'						=> 'Chosen file is not a valid file.',
'img_phperr_partial'				=> 'Image only partially uploaded.',
'img_phperr_nofile'				=> 'No file has been specified.',
'img_phperr_tempfolder'			=> "Temporary folder is missing",
'img_phperr_DiskWrite'			=> 'Error while writing file on disk.',

'succes'								=> "Success",
// Chiffres 0 à 9 pour captcha
'0'									=> 'zero',
'1'									=> 'one',
'2'									=> 'two',
'3'									=> 'three',
'4'									=> 'four',
'5'									=> 'five',
'6'									=> 'six',
'7'									=> 'seven',
'8'									=> 'eight',
'9'									=> 'nine',


);
/* ##############################################################################################
   ----------------------------------------- Nederlands -----------------------------------------*/

$lang_nl = array(
'id'								=> 'nl',
// Install
'install'							=> 'Installatie',
'install_id'						=> 'Kies en naam',
'install_mdp'						=> 'Kies en wachtwoord',
'install_remdp'					=> 'Bevestig je wachtwoord',
'install_ok'						=> 'Gefelisiteerd ! Installatie is voltooid',
'install_echec' 					=> 'Sorry, uw server is niet compatibel',
'install_connect' 					=> 'Identificeer uwzelf',
'first_titre' 					=> 'Mijn erste bericht',
'first_edit' 					=> 'Wijzig-mij',
// Wiki
'label_wiki'						=> 'Opmaak',
'wiki_titre'						=> 'Titel',
'wiki_titre_exp'					=> '! Groote titel !! Gemiddelde titel !!! Kleine titre',
'wiki_lien'							=> 'Link',
'wiki_lien_exp'						=> '[link tekst|link URL]',
'wiki_gras'							=> 'Vet',
'wiki_gras_exp'						=> '__Vet tekst__',
'wiki_italique'						=> 'Cursief',
'wiki_italique_exp'					=> '##Cursief tekst##',
'wiki_image'						=> 'Afbeelding',
'wiki_image_exp'						=> '((Beeld URL|alternative text))',
'wiki_lienimage' 					=> 'Afbeelding met link',
'wiki_lienimage_exp' 				=> '[((Afbeelding URL|Alternative text))|Link URL]',
'wiki_souligne' 					=> 'Onderstreepte',
'wiki_souligne_exp' 				=> '++onderstreepte tekst++',
'wiki_barre' 						=> 'Doorhaaling',
'wiki_barre_exp' 					=> '--doorgehaalde tekst--',
'wiki_code' 					=> 'Code',
// Navigation
'nouvelle_image'				=> 'Nieuw afbelding',
'preferences'					=> 'Instellingen',
'connexion' 					=> 'Aanmelden',
'enregistrer' 						=> 'Opslaan',
'envoyer' 							=> 'Verzenden',
'mesarticles' 					=> 'Mijn berichten',
'nouveau' 						=> 'Nieuw bericht',
'supprimer' 					=> 'Verweideren',
'deconnexion' 					=> 'Afmelden',
'rechercher' 					=> 'Zoek',
'filtrer' 							=> 'Filter',
'oui' 							=> 'Ja',
'non' 							=> 'Nee',
'ouverts' 							=> 'Toegestaan',
'fermes' 							=> 'Verboden',
'depuis' 							=> 'sinds',
'sur' 								=> 'op',
// Modes
'ecrire'							=> 'Bijwerken',
'apercu'							=> 'overzicht',
'images'						=> 'Afbeldingen',
'commentaires'						=> 'Reactie(s)',
// Labels
'label_date'					=> 'Datum',
'label_time'					=> 'Tijd',
'label_titre'						=> 'Titel',
'label_chapo'						=> 'Chapô',
'label_contenu'						=> 'Inhoud',
'label_identifiant'					=> 'Login',
'label_motdepasse'				=> 'Wachtwoord',
'label_statut'						=> 'Staatus',
'label_publie'						=> 'Gepubliceerd',
'label_brouillon'					=> 'Concept',
'label_brouillons'					=> 'Concepten',
'label_publies'						=> 'Gepubliceerd',
'label_allowcomment'				=> 'Reacties',
'label_image_ajout'					=> 'En afbeelding toevoegen',
'label_derniers'					=> 'Recente artikelen',
'label_afficher'					=> 'Bekijken',
'label_ok'						=> 'OK',
'label_article'					=> 'Bericht',
'label_articles'				=> 'Berichten',
'label_commentaire'					=> 'Reactie',
'label_commentaires'				=> 'Reacties',
// Commentaire
'aucun'								=> 'geen',
'comment_ajout'						=> 'Reagegen',
'comment_nom'						=> 'Bijnaam :',
'comment_email'					=> 'E-mail (Voord niet zichtbaar) :',
'comment_webpage'					=> 'Website (facultatief) :',
'comment_contenu'				=> '',
'comment_captcha'				=> 'Hoe veel is ',
'comment_not_allowed'				=> 'Reacties zijn gesloten voor dit artikel',
// Titles - liens
'lien_article'					=> 'Bericht zien',
'lien_blog'							=> 'Blog zien',
// Mois
'janvier'						=> 'Januari',
'fevrier'						=> 'Februari',
'mars'							=> 'Maart',
'avril'							=> 'April',
'mai'							=> 'Mei',
'juin'							=> 'Juni',
'juillet'						=> 'Juli',
'aout'							=> 'Augustus',
'septembre'						=> 'September',
'octobre'						=> 'Oktober',
'novembre'						=> 'November',
'decembre'						=> 'December',
// Jours
'lu'							=> 'Ma',
'ma'							=> 'Di',
'me'							=> 'Wo',
'je'							=> 'Do',
've'							=> 'Vr',
'sa'							=> 'Za',
'di'							=> 'Zo',
// Jours
'lundi'							=> 'Maandag',
'mardi'							=> 'Dinsdag',
'mercredi'						=> 'Woensdag',
'jeudi'							=> 'Donderdag',
'vendredi'						=> 'Vrijdag',
'samedi'						=> 'Zaterdag',
'dimanche'						=> 'Zondag',
'aujourdhui'					=> 'Vandaag',
'hier'							=> 'Gisteren',
// Erreurs
'erreurs' 							=> 'Fout(en)',
'err_connexion' 					=> 'Login en/of wachtwoord onjuist',
'err_titre' 						=> 'De title is leeg',
'err_chapo' 						=> 'Het chapô is leeg',
'err_contenu' 						=> 'De inhood is leeg',
'err_annee' 					=> 'Het jaar is niet correct',
'err_mois' 						=> 'Het maand is niet correct',
'err_jour' 						=> 'De dag is niet correct',
'err_heure' 					=> 'Het uur is niet correct',
'err_minutes' 					=> 'De minuten zijn niet correct',
'err_secondes' 					=> 'De seconden zijn niet correct',
'err_id_exist' 						=> 'Dit ID bestaad al. Bedankt voor het veranderen van de datum van bericht',
'err_data_dir_notfound' 			=> 'Het data-bestand is niet gevonden',
'err_prefs_write'					=> 'Kan het bestand met instellingen niet schrijven',
'err_prefs_auteur'					=> 'Auteur\'s naam is leeg',
'err_prefs_email'					=> 'E-mailadres is ongeldig',
'err_prefs_identifiant'				=> 'Login il leeg',
'err_prefs_id_mdp'					=> 'Om een nieuwe ID te kiesen, moet u uw wachtwoord geven',
'err_prefs_oldmdp'					=> 'Het oude wachtwoord is niet correct',
'err_prefs_mdp'						=> 'Het wachtwoord moet minstens 6 karakters lang zijn',
'err_prefs_newmdp'					=> 'Om een nieuw wachtwoord te instellen, moet u de oude opgeven',
'err_prefs_nbmax'					=> 'Het aantal artikelin is niet geldig',
'err_prefs_racine'					=> 'U moet het URL van de blog geven',
'err_prefs_racine_http'				=> 'Het URL van de blog moet beginnen met "http://"',
'err_prefs_racine_slash'			=> 'Het URL van de blog moet einden met un slash "/"',
'err_no_comment'					=> 'Alle veldel zijn verplicht om te reageren',
'err_comm_auteur'					=> 'Auteur\'s naam is leeg',
'err_comm_email'					=> 'Emailadres is ongeldig',
'err_comm_contenu'					=> 'Uw reactie is leeg',
'err_comm_captcha'					=> 'Het anti-spam som is niet correct',
// Questions
'question_suppr_article'			=> 'Bent u zeker dat u deze artikel wilt verwijderen ?',
'question_suppr_comment'			=> 'Bent u zeker dat u deze commentaar wilt verwijderen ?',
// Confirmations
'confirm_article_suppr'				=> 'Het artikel is verwijdert',
'confirm_article_ajout'				=> 'Het artikel is toegevoegd ',
'confirm_article_maj'				=> 'Het artikle is bijgewerkt',
'confirm_image_ajout'				=> 'Het afbeelding is toegevoegd',
'confirm_image_suppr'				=> 'Het afbeelding is verwijdert',
'confirm_prefs_maj'					=> 'Uw voorkeuren zijn opgeslagen',
'confirm_logout_ok'					=> 'U bent uitgemeld',
'confirm_comment_ajout'				=> 'Uw commentaar is toegevoegd',
'confirm_comment_suppr'				=> 'Het commentaar is verwijdert',
// Redirections
'retour_liste'						=> '« Lijst met berichten',
// Titres des pages
'bienvenue'						=> 'Welkom',
'titre_identification' 				=> 'Identificer u',
'titre_articles' 				=> 'Uw berichten',
'titre_ecrire' 					=> 'En nieuw bericht schrijven',
'titre_maj' 						=> 'Update van un bericht',
'titre_commentaires' 				=> 'Reacties',
'titre_preferences' 			=> 'Instellingen',
'titre_image'						=> 'Afbeeldingen',
// Preferences
'prefs_legend_utilisateur'			=> 'Login',
'prefs_legend_apparence'			=> 'Verschijning',
'prefs_legend_securite'				=> 'Veiligheid',
'prefs_legend_dateheure'		=> 'Datum en tijd',
'prefs_legend_config'				=> 'Instellingen',
'prefs_legend_image'				=> 'En afbeelfind zenden',
'pref_auteur'						=> 'Auteur',
'pref_email'					=> 'E-mail adres',
'pref_identifiant'					=> 'Login',
'pref_mdp'						=> 'Oude wachtwoord',
'pref_mdp_nouv'					=> 'Nieuwe wachtwoord',
'pref_langue'					=> 'Taal',
'pref_nom_site'						=> 'Naam van uw blog',
'pref_desc'							=> 'Beschrijving',
'pref_format_date'				=> 'Datum formaat',
'pref_format_heure'				=> 'Tijd formaat',
'pref_racine'						=> 'Adres (URL) van uw blog',
'pref_dossier_images'				=> 'Map mat afbeeldingen',
'pref_nb_maxi'						=> 'Aantal items op uw homepage',
'pref_nb_list'						=> 'Aantal itemps in de lijst',
'pref_nb_list_com'				=> 'Aantal commentaaren in de lijst',
'pref_apercu'						=> 'Overzicht',
'pref_theme'					=> 'Thema',
'pref_images'						=> 'Utiliser les images',
'pref_commentaires'					=> 'Reacties aan zeten',
'pref_aff_onglet_comm'			=> 'Reacties tabblad vergeven"',
'pref_aff_onglet_images'			=> 'Afbeldingen tabblad vergeven"',
// Notes
'note_no_article'					=> 'Geen bericht gevonden',
'note_no_comment'					=> 'Geen reacties',
'resultats_recherche'				=> 'Zoekresultaten:',
'note_no_image'						=> 'Geen afbeldingen',
//Formulaire Images
'img_nom_donnee'					=> 'Naam (optioneel) :',
'img_avert_format_nom'				=> '(cijvers en leters alleen)',
'img_upload'						=> 'Upload',
'img_upload_succes'					=> 'Het afbeelding is succesvol verzonden!',

'img_err_chmod'						=> 'Kan het bestand niet uploaden. Controleer de CHMOD van de map',
'img_err_size'						=> 'Uw bestant mag niet grooter zijn dan ',
'img_err_format'					=> 'Verkeerde bestand formaat. De toegestande formaaten zijn :',
'img_err_file'						=> 'Het bestand is geen correct afbeelding.',
'img_phperr_partial'				=> 'Het bestand is maar partiel verzonden.',
'img_phperr_nofile'					=> 'Geen bestand was gegeven.',
'img_phperr_tempfolder'				=> 'Is is geen tijdelijke map (voor PHP)',
'img_phperr_DiskWrite'				=> 'Kan het bestand niet op schijf opslaan.',

'succes'					=> "Success",
// Chiffres 0 à 9 pour captcha
'0'								=> 'nul',
'1'								=> 'een',
'2'								=> 'twee',
'3'								=> 'drie',
'4'								=> 'vier',
'5'								=> 'vijf',
'6'								=> 'zes',
'7'								=> 'zeven',
'8'								=> 'acht',
'9'								=> 'negen',


);


?>
